db.url=jdbc:mysql://127.0.0.1:3306/pidev?serverVersion=10.4.32-MariaDB&charset=utf8mb4&serverTimezone=UTC&useSSL=false
db.username=root
db.password=
news.api.key=
openaq.api.key=
huggingface.api.key=
stripe.secret.key=
stripe.payout.currency=usd
stripe.connected.account.country=US
app.base.url=http://127.0.0.1:8000
stripe.app.base.url=http://127.0.0.1:8000
